<?xml version="1.0"?>
<package format="3">
  <name>mission_explorer</name>
  <version>0.1.0</version>
  <description>ROS 2 package for Autonomous explorer solution for Homework 14 underground mapper scenario.</description>

  <maintainer email="robot-oshaleyko@yahoo.com">osha</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>underground_world</depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>